name: dark_breach_radar
description: Mobile breach radar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  workmanager: ^0.5.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.1